spring:
  application:
    name: product
  datasource:
    url: jdbc:mysql://192.168.43.115/sell?characterEncoding=utf-8&useSSl=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true
  rabbitmq:
    host: 192.168.43.115
    port: 5672
    username: admin
    password: admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
      prefer-ip-address: true

ribbon:
  eureka:
    enabled: true

server:
  port: 8081
env:
  test3
